# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfe133ab378a45ebc32b15233da9747d4d994c18599eaff47cbd11fe6326c75514ec9bee362d28cd1c5a5688eb5991d3034f00a407caa8f714310e2643bb2d77

test:
  secret_key_base: 1fb7691ea8ea1f07d6eb40885aa31955d356bcf220c2b65c4cc46e3927c70b19c3b59c99367f43293b0f8df0605979ae3095be5e8ed77e9e1e72d3f233beb4d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
